[package]
name = "nyx"
version = "0.2.5"
edition = "2021"
authors = ["Xqhare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dirs = "5.0.1"
eframe = "0.25.0"
libdrm_amdgpu_sys = "0.4.1"
sysinfo = "0.30.5"
neith = { path = "../neith" }
signal-hook = "0.3.17"
egui_plot = "0.25.0"
rand = "0.8.5"

