[package]
name = "nyx"
version = "1.0.6"
edition = "2021"
authors = ["Xqhare"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dirs = "5.0.1"
eframe = "0.25.0"
sysinfo = "0.30.5"
neith = { path = "../neith" }
signal-hook = "0.3.17"
egui_plot = "0.25.0"
rand = "0.8.5"
chrono-tz = "0.8.5"
mexprp = "0.3.1"
procfs = "0.16.0"
image = "0.24.8"
json = "0.12.4"

